apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  labels:
    app: react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-container
        image: 180294212716.dkr.ecr.eu-central-1.amazonaws.com/react-frontend:latest
        ports:
        - containerPort: 3000
